version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3"
  jobs:
    install:
      - pip install --upgrade pip
      - pip install --group docs

sphinx:
    configuration: docs/conf.py

formats: all
