import io

import pytest

from reader import InvalidFeedURLError
from reader.opml import OPMLError
from reader.opml import parse
from reader.opml import unparse
from utils import utc_datetime as datetime

OPML_INPUT = b"""\
<?xml version='1.0' encoding='utf8'?>
<opml version="2.0">
  <body>
    <outline
      type="rss"
      title="title"
      text="text"
      xmlUrl="top-level"
      htmlUrl="link"
      description="a feed"
    />
    <Outline
      Type="RSS"
      Text="Text"
      XMLURL="weird-casing"
      htmlurl="link"
    />
    <outline
      type="rss"
      title="Title"
      htmlUrl="missing-xmlurl"
    />
    <outline text="parent">
      <outline type="rss" xmlUrl="nested" />
    </outline>
  </body>
</opml>
"""


OPML_OUTPUT = b"""\
<?xml version='1.0' encoding='utf-8'?>
<opml version="2.0">
  <!-- generated by reader -->
  <head>
    <title>my feeds</title>
    <dateCreated>Fri, 01 Jan 2010 00:00:00 +0000</dateCreated>
  </head>
  <body>
    <outline type="rss" title="title" text="title" xmlUrl="top-level" htmlUrl="link" description="a feed" />
    <outline type="rss" title="Text" text="Text" xmlUrl="weird-casing" htmlUrl="link" />
    <outline type="rss" xmlUrl="nested" />
  </body>
</opml>
"""


def test_roundtrip():
    feeds = parse(io.BytesIO(OPML_INPUT))
    output = unparse(
        feeds,
        title='my feeds',
        created=datetime(2010, 1, 1),
        generator='reader',
    )
    assert output == OPML_OUTPUT


OPML_EMPTY = b"""\
<?xml version='1.0' encoding='utf-8'?>
<opml version="2.0">
  <!-- generated by https://github.com/lemon24/reader -->
  <head />
  <body />
</opml>
"""


def test_empty():
    assert parse(io.BytesIO(OPML_EMPTY)) == []
    assert unparse([]) == OPML_EMPTY


@pytest.mark.parametrize(
    'input, message',
    [
        ('', "XML error"),
        ("<?xml version='1.0' encoding='xyz'?>", "XML error"),
        ("<outline></outline>", 'expected <opml>'),
        ("<opml><a><b><c></c></b></a></opml>", 'tag depth limit'),
    ],
)
def test_parse_error(input, message):
    with pytest.raises(OPMLError, match=message):
        parse(io.BytesIO(input.encode()), max_depth=3)


def test_import_export(reader):
    reader._now = lambda: datetime(2010, 1, 1)
    reader.add_feed('http://one')
    reader.add_feed('http://two')
    reader.add_feed('reader:', allow_invalid_url=True)
    reader.add_feed('invalid:', allow_invalid_url=True)

    export = reader.export_feeds()

    assert b'reader feeds' in export.content
    assert b'01 Jan 2010' in export.content
    assert export.filename == 'reader-feeds-2010-01-01-00-00-00.opml'
    assert export.headers == {
        'Content-Type': 'application/xml; charset=utf-8',
        'Content-Disposition': f'attachment; filename="reader-feeds-2010-01-01-00-00-00.opml"',
    }

    for feed in reader.get_feeds():
        reader.delete_feed(feed)

    reader.import_feeds(io.BytesIO(export.content))
    assert {f.url for f in reader.get_feeds()} == {'http://one', 'http://two'}


def test_export_iter(reader):
    reader.add_feed('http://one')
    reader.add_feed('http://two')

    export = reader.export_feeds([reader.get_feed('http://one')])

    assert b'one' in export.content
    assert b'two' not in export.content


def test_import_iter(reader):
    reader.add_feed('http://added')
    reader.add_feed('http://exists')
    reader.add_feed('reader:', allow_invalid_url=True)

    feeds = list(reader.get_feeds())
    reader.delete_feed('http://added')

    results = {r.feed.url: r for r in reader.import_feeds_iter(feeds)}

    added = results['http://added']
    assert added.added is True
    assert added.error is None

    exists = results['http://exists']
    assert exists.added is False
    assert exists.error is None

    reader = results['reader:']
    assert reader.added is False
    assert isinstance(reader.error, InvalidFeedURLError)
