
name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        python-version: [
          "3.11", "3.12", "3.13", "3.14",
          "pypy-3.11"
        ]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:

      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        with:
          persist-credentials: false

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - run: pip install -e '.[all]' --group tests
      - run: coverage run -m pytest --runslow
      - run: ./run.sh coverage-report

      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  typing:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        with:
          persist-credentials: false

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version-file: 'pyproject.toml'

      - run: pip install -e . --group typing
      - run: mypy
