
name: publish

on:
  push:
    tags: ['[0-9]+.[0-9]+']

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        with:
          persist-credentials: false

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version-file: 'pyproject.toml'

      - run: pip install build
      - run: python3 -m build

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          path: dist

  create-release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0

      - name: create release
        run: >-
          gh release create --draft
          --repo ${{ github.repository }}
          ${GITHUB_REF_NAME}
          artifact/*
        env:
          GH_TOKEN: ${{ github.token }}

  publish-pypi:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/project/${{ github.event.repository.name }}/${{ github.ref_name }}

    steps:

      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0

      - uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247 # v1.14
        with:
          packages-dir: artifact/
