
name: publish

on:
  push:
    tags: ['[0-9]+.[0-9]+']

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version-file: 'pyproject.toml'

      - run: pip install build
      - run: python3 -m build

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: dist

  create-release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1

      - name: create release
        run: >-
          gh release create --draft
          --repo ${{ github.repository }}
          ${GITHUB_REF_NAME}
          artifact/*
        env:
          GH_TOKEN: ${{ github.token }}

  publish-pypi:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/project/${{ github.event.repository.name }}/${{ github.ref_name }}

    steps:

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1

      - uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247 # v1.14
        with:
          packages-dir: artifact/
